Conditional Statements in Python

In [3]:
number = 4
if number == 4:
    print('number equals 4')

number equals 4


In [4]:
#now we use an else
if number > 4:
    print('number greater than 4')
else:
    print('Number is not greater than 4')

Number is not greater than 4


In [5]:
#now else-if
if number > 4:
    print('number greater than 4')
elif number == 4:
    print('number equals 4')

number equals 4


In [8]:
#test multiple conditions
if (number > 3) and (number < 10):
    print('number is in (3,10)')

number is in (3,10)


In [15]:
#Or? OR WHAT!?!? Pray you don't find out...
number = 11
if (number > 3) or (number > 10)
  print('number is in (3,10)')

SyntaxError: invalid syntax (<ipython-input-15-8977e93955b6>, line 3)

In [14]:
#With Bool
test_run = False
if test_run:
    print('Test run')
else:
    print('Not test run')

Not test run


Conditions with Numpy ARRAYS

In [16]:
import numpy as np

In [17]:
a = np.random.rand(5, 5)

In [18]:
a

array([[ 0.66442786,  0.19899283,  0.66487622,  0.73727977,  0.95008392],
       [ 0.05959572,  0.7629511 ,  0.17803115,  0.48501214,  0.00231202],
       [ 0.26584657,  0.43906533,  0.11321886,  0.67270605,  0.38515164],
       [ 0.35847183,  0.45450393,  0.69345624,  0.32080485,  0.89972398],
       [ 0.80336256,  0.80183285,  0.43885735,  0.06182598,  0.25573593]])

In [19]:
b = a > 1 

In [20]:
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [21]:
a * b

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
if a > 1:
    print("a is greater than 1")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [24]:
if (a > 1).any():
    print("some a is greater than 1")

In [26]:
if (a < 1).all():
    print('all of a is less than 1')
else:
    print('Yeah Yeah Flippo!')

all of a is less than 1


Conditionals in Pandas

In [27]:
import pandas as pd

In [28]:
data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 'year': [2014, 2015, 2016, 2015, 2016], 'wins': [6, 5, 5, 10, 8]}

df = pd.DataFrame(data)
df

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015
4    UGA     8  2016

In [29]:
df['winning season'] = df['wins'] > 6

In [30]:
df

school  wins  year  winning season
0  Texas     6  2014           False
1  Texas     5  2015           False
2  Texas     5  2016           False
3    UGA    10  2015            True
4    UGA     8  2016            True

In [31]:
#True and False has gone bad and I've played for a Bool
Ball = False
Joaquin = 17
Ball * Joaquin

0

In [32]:
#an indicator based on many conditions
df['winning 2016'] = (df['wins'] > 6) & (df['year'] == 2016)
df

school  wins  year  winning season  winning 2016
0  Texas     6  2014           False         False
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False
3    UGA    10  2015            True         False
4    UGA     8  2016            True          True

In [33]:
#conditions to slice the data half in two
texas = df[df['school'] == 'Texas']
texas

school  wins  year  winning season  winning 2016
0  Texas     6  2014           False         False
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False

In [34]:
#slice with several conditions
texas_last2 = df[(df['school'] == 'Texas') & (df['year'] > 2014)]
texas_last2

school  wins  year  winning season  winning 2016
1  Texas     5  2015           False         False
2  Texas     5  2016           False         False

In [35]:
#CUT MY LIFE INTO PIECES!!! THIS IS MY LAST RESORT!!!!
#SUFFOCATION, NO BREATHING...

The Try Statement, but not the try guys

In [36]:
#Using the try statement
try:
    df = pd.read_csv('mydata.csv')
except:
    print('data is not there')

data is not there


ls vs ==

In [37]:
number = 4 
if number == 4:
    print("number is 4")

number is 4


In [38]:
if number is 4:
    print('Number is 4')

Number is 4


In [39]:
##But it must be noted that == and is are not the same 
    # == tests equality
    #is tests "identity"
a = [1, 2, 3]
b = a

In [40]:
a
b

[1, 2, 3]

In [41]:
c = [1, 2, 3]

In [42]:
#test equality
if a == c:
    print('a equals c')

a equals c


In [43]:
#test that a and c point to the same object \
if a is c:
    print('a and c are the same')
else:
    print('they are not the same, as I hope to show')

they are not the same, as I hope to show


In [44]:
if a is b:
    print('a and b are the same')
else: 
    print('a and b are not the same, as I hope to show')

a and b are the same


Stone Loops of Jurassica

In [45]:
#example of a for loop
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [47]:
#nested loops, nested loops...
for i in range(2):
    for j in range(3):
        print(i, "+", j, "=", i + j)
    print('i = ', j)

0 + 0 = 0
0 + 1 = 1
0 + 2 = 2
i =  2
1 + 0 = 1
1 + 1 = 2
1 + 2 = 3
i =  2


In [49]:
#WHILE I'M WAITING!!!
i = 0
while i  < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [50]:
#Use while loops when you have to iterate until it confess...


Loop Control
    -Break! (Open the loop to stop it)
    -Continue, continue (for your sake I hope he's not on a long journey')

In [51]:
#example of using break
for i in range(2):
    for j in range(3):
        print(i, "+", j, "=", i + j)
        break

0 + 0 = 0
1 + 0 = 1


In [53]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n/x)
            break
    else: #goes with the for x loop
        print(n, 'is a prime number')
            

2 is a prime number
3 is a prime number
4 equals 2 * 2.0
5 is a prime number
6 equals 2 * 3.0
7 is a prime number
8 equals 2 * 4.0
9 equals 3 * 3.0


In [54]:
# example of using continue - loops to finde even numbers... (thoughts arrive like BUTTERFLIES!!)
for num in range(2, 10):
    if num % 2 == 0:
        print('Found an even number')
        continue #anything after a continue is not done - go straight to the next iteration
    print('Found a number')
        

Found an even number
Found a number
Found an even number
Found a number
Found an even number
Found a number
Found an even number
Found a number


Nested loops with nested data

In [55]:
#make a list of lists
students = [("alex", ["compsci", "physics"]), ("justin", ["math", "compsci", "stats"]), ("matt", ['compsci', 'accounting', 'econ']), ('zehra', ["compsci", 'econ', 'stats'])]

In [56]:
students

[('alex', ['compsci', 'physics']),
 ('justin', ['math', 'compsci', 'stats']),
 ('matt', ['compsci', 'accounting', 'econ']),
 ('zehra', ['compsci', 'econ', 'stats'])]

In [60]:
# loop over two lists in one for loop
for (name, subjects) in students:
    print(name, " takes ", len(subjects), "courses")

alex  takes  2 courses
justin  takes  3 courses
matt  takes  3 courses
zehra  takes  3 courses


In [61]:
for (name, subjects) in students:
    for course in subjects:
        print(name, 'takes', course)

alex takes compsci
alex takes physics
justin takes math
justin takes compsci
justin takes stats
matt takes compsci
matt takes accounting
matt takes econ
zehra takes compsci
zehra takes econ
zehra takes stats


list comprehensions

In [62]:
all_files = ['bin', 'Data', 'Desktop', '.baschrc', '.ssh', '.vimrc']

In [63]:
all_files

['bin', 'Data', 'Desktop', '.baschrc', '.ssh', '.vimrc']

In [64]:
not_hidden = [name for name in all_files if name[0] != '.']

In [65]:
not_hidden

['bin', 'Data', 'Desktop']

In [66]:
numbers = [1, 2, 3, 4]
numbers ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [67]:
# lists cannot be squared after such manner
#rather do this
numbers = [1, 2, 3, 4]
squares = [x ** 2 for x in numbers]
squares

[1, 4, 9, 16]

In [70]:
#list conprehensions are also fast
import time
N = 10000
start_time = time.time()
for i in range(N):
    squares = [x ** 2 for x in numbers]
end_time = time.time()
print('List comprehension time =', end_time - start_time)
squares = []
start_time = time.time()
for i in range(N):
    for j in range(len(numbers)):
        squares.append(numbers[j] ** 2)
end_time = time.time()
print('Naive loop time =', end_time - start_time)

List comprehension time = 0.020967960357666016
Naive loop time = 0.03988289833068848


In [71]:
#Using built in things like comprehensions is generally faster

Looping over special data structures and Numpy Arrays

In [73]:
import numpy as np
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
for x in np.nditer(a[0, :]):
    print(x)

0
1
2
