Problem 1. Write a function that accepts a list of numbers as input and
returns a new list with the minimum, maximum, and average of the original
list (in that order). Remember to use floating point division to calculate the
average. Can you implement this function in a single line?

In [13]:
def summary(a):
    "We take a list of numbers and return the max, min, and average and return this as a list"
    b = max(a)
    c = min(a) 
    d = float(sum(a))/ max(len(a), 1)
    e = [b, c, d]
    return e

In [14]:
summary([1, 2, 3, 4, 5, 6, 10])

[10, 1, 4.428571428571429]

Problem 2. Python has several methods that seem to change immutable
objects. These methods actually work by making copies of objects. We can
therefore determine which object types are mutable and which are immutable
by using the equal sign and “changing” the objects.


In [16]:
>>> dict_1 = {1: 'x', 2: 'b'} # Create a dictionary.
>>> dict_2 = dict_1 # Assign it a new name.
>>> dict_2[1] = 'a' # Change the 'new' dictionary.
>>> dict_1 == dict_2 # Compare the two names.
True

True

Since altering one name altered the other, we conclude that no copy has
been made and that therefore Python dictionaries are mutable. If we repeat
this process with a di↵erent type and the two names are di↵erent in the end,
we will know that a copy had been made and the type is immutable.
Following the example given above, determine which object types are
mutable and which are immutable. Use the following operations to modify
each of the given types.
numbers num += 1
strings word += ‘a’
lists list.append(1)
tuples tuple += (1,)
dictionaries dict[1] = ‘a’
Print a statement of your conclusions.

In [17]:
num_1 = 8
num_2 = num_1
num_2 = 8 + 1
num_1 == num_2

False

In [18]:
#Thus, numbers are mutable as num_1 =/ num_2

In [36]:
word = "Vanilla Ice"
yo = word
yo = yo + "a"
word == yo


False

In [21]:
#Thus, strings are also mutable as word =/ yo

In [44]:
A = [1, 2, 3]
B = A
B.append([2, 3])
A == B

True

In [45]:
#The true value indicates that A and B are immutable objects as they were the same at genesis.

In [51]:
A = (1, 2, 3)
B = A
C = (1, 3, 6)
B = B + C
A == B

False

In [52]:
#The false response means that tuples are mutable 

In [53]:
webster = {1: 'x', 2: 'b'}
merriam = webster
webster[2] = 'a'
dict_1 == dict_2

True

In [54]:
#This means that the dictionaries are immutable as they remain the same and were so at genesis.

Problem 3. Create a module called calculator.py. Write a function that
returns the sum of two arguments, a function that returns the product of two
arguments, and a function that returns the square root of a single argument.
When the file is either run or imported, nothing should be executed.
In your main solutions file, import your new calculator module. Using
only the functions defined in the module, write a new function that calculates
the length of the hypotenuse of a right triangle given the lengths of the other
two sides.

In [65]:
cd "/Users/Alexandria/CompEcon_Fall17/PSets"

/Users/Alexandria/CompEcon_Fall17/PSets


In [67]:
import calculator as calc

In [68]:
#We now create the function that will suffer us to find the hypotenuse of a right triangle

In [71]:
def hype(val1, val2):
    "This calculator will find the hypotenuse from two legs"
    dont = multiply(val1, val1)
    believe = multiply(val2, val2)
    the = adding(dont, believe)
    c = (the) ** (0.5)
    return c

In [72]:
hype(3, 4)

5.0

We now move on to Question 2

Problem 1. NumPy’s dot() function performs matrix multiplication. Write
a function that defines the following matrices as NumPy arrays.


$$
A = \begin{bmatrix} 
3 & -1 & 4 \\ 1 & 5 & -9 \\ 
\end{bmatrix} 
$$

$$
B = \begin{bmatrix}
2 & 6 & -5 & 3 \\
5 & -8 & 9 & 7 \\
9 & -3 & -2 & -3 \\
\end{bmatrix}
$$
Return the matrix product AB. NumPy has excellent documentation. For examples of array initialization and matrix multiplication, use IPython’s object introspection feature to look up the documentation for np.ndarray, np.array() and np.dot()

In [80]:
clear

In [81]:
import numpy as num

In [98]:
def dproduct(A, B):
    "THIS IS Matrix Multiplication with the above matrices"
    A = num.array([[1,-3, 4], [1, 5, -9]])
    B = num.array([[2, 6, -5, 3], [5, 8, 9, 7], [9, -3, -2, -3]])
    AB = num.dot(A, B)
    return AB

In [99]:
dproduct(A, B)

array([[ 23, -30, -40, -30],
       [-54,  73,  58,  65]])

Problem 2. Write a function that defines the following matrix as a NumPy
array.
$$
A = \begin{bmatrix} 
3 & 1 & 4 \\ 
1 & 5 & 9 \\
-5 & 3 & 1 \\
\end{bmatrix} 
$$
Return the matrix  $-A^3 + 9A^2  - 15A$.
In this context, $A^2 = AA$ (the matrix product). The somewhat surprising
result is a demonstration of the Cayley-Hamilton theorem.

In [23]:
def CayHam():
    "This reproduces a result of the Cayley-Hamilton Theorem"
    A = num.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
    A2 = num.dot(A, A)
    A3 = num.dot(A2, A)
    final = (-1 * (A3)) + (9 * (A2)) - (15 * A)
    return final

In [24]:
CayHam()


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 5. Write a function that defines the following matrices as NumPy
arrays.
$$
A = \begin{bmatrix} 
0 & 2 & 4 \\ 
1 & 3 & 5 \\ 
\end{bmatrix} 
$$

----------------------

$$
B = \begin{bmatrix} 
3 & 0 & 0 \\ 
3 & 3 & 0 \\
3 & 3 & 3 \\
\end{bmatrix} 
$$

----------------------

$$
C = \begin{bmatrix} 
-2 & 0 & 0 \\ 
0 & -2 & 0 \\
0 & 0 & -2 \\
\end{bmatrix} 
$$
----------------------

Use NumPy’s stacking functions to create and return the block matrix:

$$
\begin{bmatrix} 
0 & A^T & I \\ 
A & 0 & 0 \\
B & 0 & C \\
\end{bmatrix} 
$$

where I is the identity matrix of the appropriate size and each 0 is a matrix
of all zeros, also of appropriate sizes.
A block matrix of this form is used in the Interior Point method for linear
optimization.

In [5]:
import numpy as num
def bigmat():
    "This creates a big matrix out of all the following small matrices"
    A = num.array([[0, 2, 4], [1, 3, 5]])
    B = num.array([[3, 0, 0], [3, 3, 0], [3, 3, 3]])
    C = num.array([[-2, 0, 0], [0, -2, 0], [0, 0, -2]])
    mat1 = num.hstack((num.zeros((3,3)), A.T, num.eye(3)))
    mat2 = num.hstack((A, num.zeros((2,2)), num.zeros((2, 3))))
    mat3 = num.hstack((B, num.zeros((3, 2)), C))
    bmat = num.vstack ((mat1, mat2, mat3))
    return bmat

In [6]:
bigmat()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

Problem 1. Expand the Backpack class to match the following specifications.
1. Modify the constructor so that it accepts a name, a color, and a maximum
size (in that order). Make max_size a default argument with
default value 5. Store each input as an attribute.
2. Modify the put() method to ensure that the backpack does not go over
capacity. If the user tries to put in more than max_size items, print “No
Room!” and do not add the item to the contents list.
3. Add a new method called dump() that resets the contents of the backpack
to an empty list. This method should not receive any arguments
(except self).
To ensure that your class works properly, consider writing a test function
outside outside of the Backpack class that instantiates and analyzes a Backpack
object. Your function may look something like this:

In [2]:
class Backpack(object):
    """A Backpack object class. Has a name and a list of contents.
    Attributes:
    name (str): the name of the backpack's owner.
    contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        """Set the name and initialize an empty contents list.
        Inputs:
        name (str): the name of the backpack's owner.
        Returns:
        A Backpack object wth no contents.
        """
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):
        """Add 'item' to the backpack's list of contents."""
        if len(self.contents) < self.max_size:
            self.contents.append(item)
        if len(self.contents) >= self.max_size:
            print("No More Room!")
            
    def dump(self):
        self.contents = []

In [26]:
pack = Backpack("Zannah", "Black")

In [28]:
pack.put("Jedi Holocron")

In [29]:
pack.put("Bane's Lightsaber")
pack.put("Telos Holocron")
pack.put("Sith Amulet")
pack.put("Naga Sadow's Battle Sword")

No More Room!


In [30]:
pack.contents

['Jedi Holocron',
 "Bane's Lightsaber",
 'Telos Holocron',
 'Sith Amulet',
 "Naga Sadow's Battle Sword"]

In [32]:
pack.dump()

In [33]:
pack.contents

[]

Problem 2. Create a Jetpack class that inherits from the Backpack class.
1. Overwrite the constructor so that in addition to a name, color, and
maximum size, it also accepts an amount of fuel. Change the default
value of max_size to 2, and set the default value of fuel to 10. Store the
fuel as an attribute.
2. Add a fly() method that accepts an amount of fuel to be burned and
decrements the fuel attribute by that amount. If the user tries to burn
more fuel than remains, print “Not enough fuel!” and do not decrement
the fuel.
3. Overwrite the dump() method so that both the contents and the fuel
tank are emptied.

In [71]:
class Jetpack(Backpack):
    "Subclass of Backpack"
    def __init__(self, name, color, max_size = 2, fuel = 10): 
        """Set the name and initialize an empty contents list.
        Inputs:
        name (str): the name of the backpack's owner.
        Returns:
        A Backpack object wth no contents.
        """
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        self.fuel = fuel
    def fly(self, dist):
        "When the user uses the jetpack for locomotion"
        if dist < self.fuel:
            self.fuel = self.fuel - dist
            print(dist, self.fuel)
        else:
            print("Not enough fuel!")
            
    def dump(self):
        self.contents = []
        self.fuel = []
    
    def refuel(self):
        self.fuel = 10

In [72]:
jpack = Jetpack("Boba Fet", "Silver")

In [73]:
jpack.fuel

10

In [74]:
jpack.fly(7)

7 3


In [75]:
jpack.fly(4)

Not enough fuel!


In [76]:
jpack.dump()

In [78]:
jpack.contents

[]

In [79]:
jpack.fuel

[]